### ISSUE TITLE
Content-Type and Accept

### ISSUE THREAD

**Issue by 1995parham** [powerman/rpc-codec#20]
As mentioned in [JSON-RPC over HTTP specification](http://www.jsonrpc.org/historical/json-rpc-over-http.html) Content-Type *SHOULD* be `application/json-rpc` but *MAY* be `application/json` or `application/jsonrequest` and The Accept *MUST* be specified and *SHOULD* read `application/json-rpc` but MAY be `application/json` or `application/jsonrequest`. Is there any chance for supporting this specification in `http.go`?

**Comment by powerman** [comment]
This spec is irrelevant: it's about JSON-RPC 1.0 and way too old, while this package is JSON-RPC 2.0 only. Actual spec for JSON-RPC 2.0 is mentioned in README and well supported.
