### ISSUE TITLE
Add example of handling batch requests

### ISSUE THREAD

**Issue by Phrlog** [powerman/rpc-codec#25]
I didn't find any example of server with batch requests.

It would be appreciated if you add some :)

**Comment by powerman** [comment]
Server handle batch requests automatically, so there is no difference on server side.

**Comment by Phrlog** [comment]
When I followed [specification](https://www.jsonrpc.org/specification), I was getting parser error. After removing comma between requests, it works fine.

Is it OK?

**Comment by powerman** [comment]
If correct per spec request request in parser error then it's not OK. But this package has a tests for batch requests, so I believe batch should work. So, if you think there is a bug, then provide more details - what exactly you've sent, and which response you get.

**Comment by Phrlog** [comment]
Sorry, looks like it was my fault. Tried again and everything works.
