### ISSUE TITLE
Bug: Builtin type can not send as params direct. 

### ISSUE THREAD

**Issue by rocket049** [powerman/rpc-codec#26]
When i send Builtin type as params direct.
It report errors like this.

```
arith error:{"code":-32603,"message":"unsupported param type: string"}
arith error:{"code":-32603,"message":"unsupported param type: int"}

```

**Comment by powerman** [comment]
Allowed param types are: Array, Slice, Map or Struct plus Ptr to these types. This is required by [specification](https://www.jsonrpc.org/specification#parameter_structures).

**Comment by rocket049** [comment]
Thanks, I see.
