### ISSUE TITLE
Custom field in Call

### ISSUE THREAD

**Issue by AntonioBusillo** [powerman/rpc-codec#28]
Hello,
I'm using your rpc-codec library in order to create a wrapper from Zabbix' API. 

https://zabbix.com/documentation/4.0/manual/api

In their documentation they use a custom field "Auth" containing a token obtained after the login. How can I make a call with customs field like this?

`{
    "jsonrpc": "2.0",
    "method": "host.get",
    "params": {
        "output": [
            "hostid",
            "host"
        ],
        "selectInterfaces": [
            "interfaceid",
            "ip"
        ]
    },
    "id": 2,
    "auth": "0424bd59b807674191e7d77572075f33"
}`

**Comment by powerman** [comment]
There is no `"auth"` key in JSON-RPC 2.0 protocol - looks like Zabbix using their own protocol based on JSON-RPC 2.0. At a glance there is no easy way to add such a feature in general way, so probably the best you can do is fork this module and modify it to include `"auth"` key.
