### ISSUE TITLE
example to use tcp as transport

### ISSUE THREAD

**Issue by deshmukhrajvardhan** [powerman/rpc-codec#36]
Hi,

Is there an example where we use tcp as transport and have the params as json (encoded) string.
The below code gives me 
`error:invalid character 'C' looking for beginning of value
exit status 1`
```
package main

import (
	"encoding/json"
	"log"
	"net"
	"net/rpc/jsonrpc" 
        "github.com/powerman/rpc-codec"
)

var params interface{}

func main() {

	conn, err := net.Dial("tcp", "localhost:7777") // works fine

	if err != nil {
		panic(err)
	}
	defer conn.Close()

	con := jsonrpc.NewClient(conn)

	var paramsJSON string
	paramsJSON = `` //`{"namedArg1":"value"}`
	err = json.Unmarshal([]byte(paramsJSON), &params)
	var result interface{}
	err1 := con.Call("help", params, &result)
	if err1 != nil {
		log.Fatal("error:", err1)
	}
	log.Printf("%v", reply)
}
```

**Comment by powerman** [comment]
Package example contains both TCP server and client. It's available at godoc, but you can check it in the repo: https://github.com/powerman/rpc-codec/blob/master/jsonrpc2/example_test.go#L118 and https://github.com/powerman/rpc-codec/blob/master/jsonrpc2/example_test.go#L144.

**Comment by powerman** [comment]
As for your code example, it imports and uses wrong package (JSON-RPC 1.0 from stdlib).

**Comment by deshmukhrajvardhan** [comment]
Thanks @powerman.
I was earlier trying to use the lower level function calls that you use here
https://github.com/powerman/rpc-codec/blob/c72a4f8142c5cba1107b0973aedb0ab6f5513d9a/cmd/jsonrpc2client/main.go

Thanks for the help!!
