### ISSUE TITLE
Add support for "application/json-rpc"?

### ISSUE THREAD

**Issue by zj8487** [powerman/rpc-codec#7]

**Comment by powerman** [comment]
What's for? [Standard](http://www.simple-is-better.org/json-rpc/transport_http.html) says "`Content-Type:` MUST be `application/json`.".

**Comment by zj8487** [comment]
(this python lib)[https://github.com/joshmarshall/jsonrpclib] return the ```application/json-rpc ```.
maybe i should change the python lib

**Comment by powerman** [comment]
This is now possible, see https://github.com/powerman/rpc-codec/pull/9#issuecomment-233989611 for more details.
